name : Shell Commands

on: [push]

jobs:
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello Github Actions"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Pyton Command
        run: |
          import platform
          print (platform.processor())
        shell: python
          